### ISSUE TITLE
解决ijk第一次初始化时异步线程调用主线程造成的线程卡顿问题

### ISSUE THREAD

**Issue by zj381652512** [poholo/MCIJKPlayer#1]
你好,请问这个Framework是你解决"ijk第一次初始化时异步线程调用主线程造成的线程卡顿"问题后,打的包吗?

**Comment by poholo** [comment]
对的，使用请pod 'MCIJKPlayer'
由于Github单文件限制100M 仓库移到腾讯云 MCIJKPlayer https://dev.tencent.com/u/lp_mr/p/MCIJKPlayer/git
