### ISSUE TITLE
打包报错Undefined symbols for architecture armv7:

### ISSUE THREAD

**Issue by FxDepths** [poholo/MCIJKPlayer#2]
Undefined symbols for architecture armv7:
  "_ijkav_register_ijkio_protocol", referenced from:
      _ijkav_register_all in IJKMediaFramework(allformats.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by poholo** [comment]
由于Github单文件限制100M 仓库移到腾讯云 MCIJKPlayer https://dev.tencent.com/u/lp_mr/p/MCIJKPlayer/git

**Comment by poholo** [comment]
你的问题原因以及解决办法
第一种方法. 你用的xcode以及macos系统版本较低，升级系统，放弃对armv7 armv7s支持
第二种方法. 使用包含了armv7 armv7s的ijk库，比如pod 'IJKMediaFramework'
