### ISSUE TITLE
rtsp视频流播不了

### ISSUE THREAD

**Issue by devchena** [poholo/MCIJKPlayer#4]
请问作者可以扩展对rtsp协议的支持吗

**Comment by poholo** [comment]
没有开启rtsp，这类需求貌似目前不是太多，建议您自己编译一个版本。

**Comment by devchena** [comment]
主要是对修复暴力切换时的crash和线程阻塞这两个问题没有修复思路，但是又有rtsp的需求。不过还是感谢作者的开源。

**Comment by poholo** [comment]
这个库的编译是从我fork的ijk上编译得来的（处理的线程检查问题），你可以尝试在我的forked代码上加上rtsp编译，https://github.com/poholo/ijkplayer

**Comment by devchena** [comment]
谢谢大佬👍
