### ISSUE TITLE
播放视频，报错invalidateRenderBuffer

### ISSUE THREAD

**Issue by tang786472181** [poholo/MCIJKPlayer#5]
通过IJKFF初始化的player，播放报错invalidateRenderBuffer，请教一下，如何解决呀，谢谢

**Comment by poholo** [comment]
用这个
```
https://e.coding.net/lp_mr/MCIJKPlayer.git [由于coding网设置,故需要登录才能看到项目]
pod 'MCIJKPlayer'
```
此项目目录下的IJKMediaFramework.framework很久没更新,估计有问题

**Comment by taojeff** [comment]
@poholo 你的这个IJKMediaFramework.framework也是下载blibli的源码编译出来的嘛？

**Comment by poholo** [comment]
MCIJKPlayer是ijkplayer iOS 编译后的IJKMediaFramework.framework库,支持arm64/x86_64, 解决xcode9后线程检查造成的问题.

https://github.com/poholo/ijkplayer
