### ISSUE TITLE
你好，麻烦问一下，framework编译的时候，持编解码器/格式 module-lite.sh是选的哪个。coding那个地址找不到项目

### ISSUE THREAD

**Issue by wangxiaojie0379** [poholo/MCIJKPlayer#7]
module-default.sh: 更多的编解码器/格式
module-lite-hevc.sh: 较少的编解码器/格式(包括 hevc)
module-lite.sh: 较少的编解码器/格式(默认)

**Comment by poholo** [comment]
我用的是默认的，优化的也只是iOS这块的代码，
coding的地址
https://lp_mr.coding.net/public/MCIJKPlayer/MCIJKPlayer/git/files

**Comment by wangxiaojie0379** [comment]
好的，谢谢

**Comment by wangxiaojie0379** [comment]
> 我用的是默认的，优化的也只是iOS这块的代码， coding的地址 https://lp_mr.coding.net/public/MCIJKPlayer/MCIJKPlayer/git/files

**Comment by wangxiaojie0379** [comment]
好的，谢谢
